version: '3.1'

services:
  jenkins:
    build: ./jenkins
    hostname: jenkins01
    ports:
      - 9090:8080
  selenium:
    build: ./selenium
    hostname: selenium01
    ports:
      - 5901:5901
#  postgres:
#    build: ./postgres
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_PASSWORD: password
#    volumes:
#      #- ./postgres/data:/var/lib/postgresql/data 
#      - postgres_volume:/var/lib/postgresql/data
  mariadb:
    build: ./mariadb
    hostname: mariadb02
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      #- ./mariadb/mysql:/var/lib/mysql
      - mariadb_volume:/var/lib/mysql
  wildfly:
    build: ./wildfly
    hostname: wildfly03
    depends_on:
#      - postgres
      - mariadb
    ports:
      - 8080:8080
      - 9990:9990
#  liberty:
#    build: ./liberty
#    depends_on:
##      - postgres
#      - mariadb
#    ports:
#      - 9080:9080

  mongodb:
    # コンテナイメージを指定（image:コンテナイメージ名:タグ名）
    build: ./mongodb
    # コンテナのデータをボリュームとしてホストOSにマウント
    volumes:
      # MongoDBのデータをマウント
      - ./data/mongodb:/data/db
    # MongoDBのjournalファイルをsmallfilesとする
    command: mongod --smallfiles --bind_ip_all
   
  rocketchat:
    # コンテナイメージを指定（image:コンテナイメージ名:タグ名）
    build: ./rocketchat
    volumes:
      - ./data/uploads:/app/uploads
    depends_on:
      - mongodb
    # 環境変数を設定
    environment:
      # MongoDB（mongodb）のURLを指定
      - MONGO_URL=mongodb://mongodb:27017/rocketchat
      # RocketChatのURL（ここではホスト名をlocalhostとしています）
      - ROOT_URL=http://localhost:3000/
      # アカウントのメールアドレスのドメインチェックを無効化
      - Accounts_UseDNSDomainCheck=false
    # RocketChatのポートを設定
    ports:
      - 3000:3000
  
  hubot:
    build: ./hubot
    depends_on:
      - rocketchat
    volumes:
      # hubotscriptsのコンテナのデータをボリュームとしてホストOSにマウント
      - ./data/hubot:/var/www/hubotscripts
    environment:
      # RocketChatのURL（環境に合わせてIPアドレスを修正）
      - ROCKETCHAT_URL=rocketchat:3000
      # 連携させるチャンネル名
      - ROCKETCHAT_ROOM=GENERAL
      # RocketChatにログインするための認証情報（ユーザーとパスワード）
      - ROCKETCHAT_USER=bot
      - ROCKETCHAT_PASSWORD=password
      # bot名
      - BOT_NAME=RocketchatBot
      # 外部スクリプト
      - _EXTERNALSCRIPTS=hubot-diagnostics,hubot-help,hubot-seen,hubot-links,hubot-greetings
      #- _EXTERNALSCRIPTS=hubot-diagnostics,hubot-help,hubot-seen,hubot-links,hubot-greetings,hubot-jenkins-notifier
      #
      # Jenkins設定
      #
      - HUBOT_JENKINS_URL=http://jenkins:8080
      - HUBOT_JENKINS_USER=admin
      - HUBOT_JENKINS_PASSWORD=4aac8e9aeca0930ab4a42b98ed8c05a4
      - HUBOT_JENKINS_ROOM=general
      #
      # Jenkins設定(未使用)
      #
      # JenkinsのURL（環境に合わせてIPアドレスを修正）
      #- HUBOT_JENKINS_URL=http://jenkins:8080
      # Jenkinsにログインするための認証情報（ユーザーとパスワード）
      #- HUBOT_JENKINS_AUTH=admin:password

volumes:
  mariadb_volume:
    driver: 'local'
  postgres_volume:
    driver: 'local'
