version: '3.1'

services:
#  postgres:
#    build: ./postgres
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_PASSWORD: password
#    volumes:
#      - ./postgres/data:/var/lib/postgresql/data 
  mariadb:
    build: ./mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mariadb/mysql:/var/lib/mysql
  wildfly:
    build: ./wildfly
    depends_on:
#      - postgres
      - mariadb
    ports:
      - 8080:8080
      - 9990:9990
#  liberty:
#    build: ./liberty
#    depends_on:
#      - postgres
##      - mariadb
#    ports:
#      - 9080:9080
